### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - azure-servicefabric.TestErrorChaosEvent.kind
      - azure-servicefabric.TestErrorChaosEvent.reason
      - azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    langs:
      - typeScript
    type: interface
    summary: |-
      <span data-ttu-id="89e03-101">Chaos エンジンで予期しないイベントが発生したときに生成される混乱イベントについて説明します。</span><span class="sxs-lookup"><span data-stu-id="89e03-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>
      <span data-ttu-id="89e03-102">たとえば、エンティティの障害発生中に一貫性があり、中、クラスター スナップショットにより Chaos が見つかりましたこと、エンティティが既にエラーが発生しました--予期しないイベントであります。</span><span class="sxs-lookup"><span data-stu-id="89e03-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.kind
    name: kind
    fullName: kind
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="89e03-103">ポリモーフィックな識別子</span><span class="sxs-lookup"><span data-stu-id="89e03-103">Polymorphic Discriminator</span></span>
    syntax:
      content: 'kind: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: '<span data-ttu-id="89e03-104">TestErrorChaosEvent が生成された理由について説明します。</span><span class="sxs-lookup"><span data-stu-id="89e03-104">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="89e03-105">たとえば、Chaos はしようとするパーティションの障害が、TestErrorEvent が生成される、パーティションは、フォールト トレラントではない理由を示すそのパーティションは、フォールト トレラントでは不要になったを検索します。</span><span class="sxs-lookup"><span data-stu-id="89e03-105">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>'
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.timeStampUtc
    name: timeStampUtc
    fullName: timeStampUtc
    children: []
    langs:
      - typeScript
    type: property
    summary: <span data-ttu-id="89e03-106">この混乱イベントが生成されたときの UTC のタイムスタンプ。</span><span class="sxs-lookup"><span data-stu-id="89e03-106">The UTC timestamp when this Chaos event was generated.</span></span>
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type:
          - Date
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent